### ISSUE TITLE
how to change the backbone?

### ISSUE THREAD

**Issue by ranpin** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#61]
Hello authors, thank you very much for your work, I'm trying to do some experiments in modifying the SEEM visual backbone, and I have some questions that I hope to ask you.

I found that the model is doing the inference process by first loading the SEEM weights file, e.g. **seem_focall_v1.pt**, and the configuration file, e.g. **seem_focall_lang.yaml**. and then constructing the backbone through the configuration file.

The problem is: if I want to replace backbone with resnet50 (which you provided in the project), or some other network. I tried to change the configuration in sem_focall_lang.yaml, but at the beginning I still have to load sem_focall_v1.pt and they create a conflict, for example there will be **dimension mismatch issues**.

I modified the sem_focall_lang.yaml as follows：
```
BACKBONE:
    NAME: resnet
    PRETRAINED: ''
    LOAD_PRETRAINED: false
    RESNETS:
      DEPTH: 50
      WIDTH_PER_GROUP: 64
      NORM: FrozenBN
      STEM_IN_CHANNELS: 3
      STEM_OUT_CHANNELS: 64
      RES2_OUT_CHANNELS: 256
      STRIDE_IN_1X1: True
      RES5_DILATION: 1
      FREEZE_AT: 2
      OUT_FEATURES: ["res2", "res3", "res4", "res5"]
      NUM_GROUPS: 1
      DEFORM_ON_PER_STAGE: [False, False, False, False]
      DEFORM_MODULATED: False
      DEFORM_NUM_GROUPS: 1
```

For this I don't know how to solve it, can you give me some suggestions?
